name: write

frontend:
  component: '@serverless/tencent-website'
  # refer to: https://github.com/serverless-components/tencent-website/blob/master/docs/configure.md
  inputs:
    region: ${env.REGION}
    bucketName: ${name}
    protocol: https
    code:
      src: src
      root: frontend
      hook: echo npm run build
      envPath: src
    env:
      # get api url after below api service deployed.
      #apiUrl: ${api.url}

